# docker-compose.dev.yml
version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file: .env
    command: >
      uvicorn backend.api.main:app
      --host ${API_HOST}
      --port ${API_PORT}
      --reload
    environment:
      - PYTHONPATH=/app/backend
      - DEBUG=${DEBUG}
      - MAX_SCORE=${MAX_SCORE}
      - MAX_ROUNDS=${MAX_ROUNDS}
      - BOT_ENABLED=${BOT_ENABLED}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
